config/routes.rb
Rails.application.routes.draw do
  
  # ルートを　app\views\pages\home.html.erb　に設定
  root 'pages#home'
  
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {registrations: 'registrations'}

  get 'pages/home'
  get '/users', to:'users#show'
  get 'rooms/index'
  
  resources :users, only: [:show, :update]
  
  resources :rooms
  
  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    
  belongs_to :user
  belongs_to :room

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :person, numericality: true
  
end

app/models/room.rb
class Room < ApplicationRecord
    
  belongs_to :user
  has_many :bookings

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, numericality: true
  validates :image, presence: true
  validates :address, presence: true
  

  def self.search(search)
    if search
      Room.where(['address LIKE ? OR name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Room.all
    end
  end
  
  mount_uploader :image, ImagesUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :full_name, presence: true, length: {maximum: 50}
         
  has_many :rooms
  has_many :bookings
  
  attr_accessor :current_password
  
  has_one_attached :avatar
  
  mount_uploader :image, ImagesUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protect_from_forgery with: :exception
    protect_from_forgery with: :null_session
  
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :description, :image])
    end
    
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.new(params.require(:booking).permit(:price, :start_date, :end_date, :person, :total_days, :room_id))
    @booking.total_days = @booking.room.price * (@booking.end_date - @booking.start_date).to_i * @booking.person.to_i
    if @booking.save
      flash[:notice] = "予約情報は正しいですか？"
      redirect_to @booking
    else
      flash[:alert] = "予約に失敗しました。"
      @room = @booking.room
      render "rooms/show"
    end
  end

  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    flash[:notice] = "予約が完了しました。"
    redirect_to :bookings
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "予約をキャンセルしました。"
    redirect_to :bookings
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    
    def update_resource(resource, params)
      if params[:password].present? && params[:password_confirmation].present?
        resource.update_with_password(params)
      else
        resource.update_without_password(params)
      end
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @rooms = Room.all
  end
 
  def search
    @roms = Room.search(params[:search])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = current_user.rooms.new(params.require(:room).permit(:name, :introduction, :price, :address, :image))
    if @room.save
      flash[:notice] = "お部屋を保存しました。"
      redirect_to :rooms
    else
      flash[:alert] = "登録エラー。"
      render "new"
    end
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "削除しました。"
    redirect_to :rooms
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
      @user = User.find(params[:id])
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = current_user
      if @user.update(current_user_params)
          flash[:notice] = "保存しました。"
      else
          flash[:alert] = "更新できません。"
      end
      redirect_to :users
  end

  def destroy
  end
  
  private
  def current_user_params
    params.require(:user).permit(:about, :status, :avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def avatar_url(user)
        if user.avatar.attached?
            url_for(user.avatar)
        elsif user.image?
            user.image
        else
            ActionController::Base.helpers.asset_path('icon_default_avatar.jpg')
        end
    end    
    
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">

    <div style="margin-bottom: 30px;">
      <div class="col-md-4 text-center d-grid gap-2 col-6 mx-auto d-flex">
        <%= link_to " ルーム登録", new_room_path, class: "btn btn-default" %>
        </br>
        <%= link_to " 登録ルーム一覧", rooms_path, class: "btn btn-default" %>
      </div>
    </div>

    <div class="col-md-15">
      <div class="text-center">
        <div class="card card-default text-center">
          <div class="card-heading">
          予約ルーム一覧
          </div>
          </br>

          <table>
            <thead>
              <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th></br></br>
                <th class="text-nowrap" style="width: 100px;">合計料金</th>
                <th class="text-nowrap" style="width: 120px;">チェックイン</th>
                <th class="text-nowrap">チェックアウト</th>
                <th>予約確定日時</th>
              </tr>
            </thead>

            <tbody>
              <% @bookings.each do |booking| %>
                <tr>
                  <td class="td"><img src="<%= booking.room ? booking.room.image_url : '' %>" class="img-index"></td>
                  <% if booking.room %>
                    <td class="td text-nowrap"><%= link_to booking.room.name , room_path(booking.room) %></td>
                    <td class="td" style="width: 200px;"><%= booking.room.introduction %></td>
                  <% else %>
                    <%= booking.inspect %>
                  <% end %>
                  <td class="td"> &yen; <%= booking.total_days.to_i %></td>
                  <td class="td"><%= booking.start_date %></td>
                  <td class="td"><%= booking.end_date %></td>
                  <td class="td"><%= booking.created_at %></td>
                  <td><%= link_to "キャンセル", booking, method: :delete, data: { confirm: "本当にキャンセルしますか？" }, class: "btn btn-normal text-nowrap" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 d-grid gap-2 col-6 mx-auto">
      <div class="card card-default">

        <div class="card-heading align-middle text-center">
          予約内容確認
        </div>

        <div class="card-body">
          <h3 class="form-group" style="padding-bottom: 10px; border-bottom: 1px solid #eaedef;">&yen; <%= @booking.room.price.to_i %> / 日</h3>

          <div class="form-group">
            <label style="margin-bottom: 5px;">チェックイン</label>
            <div class="form-control" style="background-color: #e9ecef;"><%= @booking.start_date %></div>
          </div>

          <div class="form-group">
            <label style="margin-bottom: 5px;">チェックアウト</label>
            <div class="form-control" style="background-color: #e9ecef;"><%= @booking.end_date %></div>
          </div>

          <div class="form-group">
            <label style="margin-bottom: 5px;">宿泊日数：</label>
            <%= (@booking.end_date - @booking.start_date).to_i %>日

          </div>

          <div class="form-group">
            <label style="margin-bottom: 5px;">宿泊人数：</label>
            <%= @booking.person.to_i %>人
          </div>

          <div class="form-group" style="border-bottom: 1px solid #eaedef; padding-bottom: 20px;">
            <label style="margin-bottom: 5px;">合計金額</label>
            <div class="form-control" style="background-color: #e9ecef; "><%= @booking.total_days.to_i %>円</div>
          </div>

          <%= form_for @booking do |f| %>
            <div class="form-group">
              <%= f.submit "予約確定", class:"btn btn-blue btn-block" %>
            </div>
          <% end %>

            <div class="form-group">
              <%= link_to " ルーム詳細に戻る", :back, class: "btn btn-default btn-block" %>
            </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--　アイコン　Font Awesome　-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- cssを手伝ってくれるBootstrap -->
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <!-- ナビゲーションバー　-->
    <%= render "shared/navbar" %>
    <!-- noty -->
    <%= render "devise/shared/notification" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="top">
  <div class="container">
    <div class="area">
      <div class="form-area" style="margin-left: 60px;">
        <h3 class="form-title"> 次はどこに行きましょう</h3>
        </br>
        <%= form_tag rooms_path, :method => 'get' do %>
          <div class="form-title">
            <%= text_field_tag :search, params[:address], placeholder: "エリア", class: "form-control" %>
            <%= submit_tag "Search", :name => nil, class:"form-control btn btn-normal" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="field" style="background-color: #fff;">
  <div class="container">
    <div class="city d-flex">
      <div class="card-area m-5">
        <h3 class="form-title" style="margin-top: 30px; font-weight: bold;">
          おすすめのエリア
        </h3>
        <div class="row">
          <div class="panel-item col-lg-3 col-6">
            <%= link_to image_tag("img_tokyo.jpg", class:"card-image"), rooms_path(search:'東京') %>
          </div>
          <div class="panel-item col-lg-3 col-6">
            <%= link_to image_tag("img_osaka.jpg", class:"card-image"), rooms_path(search:'大阪') %>
          </div>
          <div class="panel-item col-lg-3 col-6">
            <%= link_to image_tag("img_kyoto.jpg", class:"card-image"), rooms_path(search:'京都') %>
          </div>
          <div class="panel-item col-lg-3 col-6">
            <%= link_to image_tag("img_hokkaido.jpeg", class:"card-image"), rooms_path(search:'北海道') %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">

    <div style="margin-bottom: 30px;">
      <div class="col-md-4 text-center d-grid gap-2 col-6 mx-auto d-flex">
        <%= link_to " ルーム登録", new_room_path, class: "btn btn-default" %>
        </br>
        </br>
        <%= link_to " 予約ルーム一覧", bookings_path, class: "btn btn-default" %>
      </div>
    </div>

    <div class="col-md-15">
      <div class="text-center">
        <div class="card card-default text-center">
          <div class="card-heading form-group" >
            登録ルーム一覧
          </div>

          <table>
            <thead>
              <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>作成日</th>
              </tr>
            </thead>

            <tbody>
              <% @rooms.each do |room| %>
                <tr>
                  <td class="td" ><img src="<%= room.image_url %>" class="img-index"></td>
                  <td class="td text-nowrap" style="width: 100px;"><%= link_to room.name, room %></td>
                  <td class="td" style="width: 200px;"><%= room.introduction %></td>
                  <td class="td" style="width: 100px;"> &yen; <%= room.price.to_i %></td>
                  <td class="td"><%= room.created_at.to_s(:date_jp) %></td>
                  <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-default text-nowrap" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-2">
      <%= link_to " 登録ルーム一覧", rooms_path, class: "btn btn-default" %>
      </br></br>
      <%= link_to " 予約ルーム一覧", bookings_path, class: "btn btn-default" %>
    </div>

    <div class="col-md-8 text-center margin">
      <div class="card card-default">
        <div class="card-heading align-middle">新しいルームを作る</div>
        <div class="card-body">
          <div class="container">

            <%= render "shared/error", obj: @room %>
            <%= form_for @room do |f| %>
            
              <div class="form-group">
                <label class="label">ルーム名</label>
                <%= f.text_field :name, autofocus: true, autocomplete: "ルーム名", placeholder: "ルーム名を入力",class: "form-control" %>
              </div>

              <div class="form-group">
                <label class="label">ルーム紹介</label>
                <%= f.text_area :introduction, rows: 5, cols: 25, autofocus: true, autocomplete: "ルーム紹介", placeholder: "ルーム説明を入力", class: "form-control" %>
              </div>

              <div class="form-group">
                <label class="label">料金</label>
                <%= f.number_field :price, autofocus: true, autocomplete: "料金", placeholder: "1日あたりの料金を入力", class: "form-control" %>
              </div>

              <div class="form-group">
                <label class="label">住所</label>
                <%= f.text_field :address, autofocus: true, autocomplete: "住所", placeholder: "住所を入力", class: "form-control" %>
              </div>

              <div class="form-group">
                <label class="label">ルーム画像</label></br>
                <button type="button" class="btn btn-outline-secondary rounded-pill">
                  <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
                </button>
              </div>

              <div class="actions">
                <%= f.submit "登録", class:"btn btn-normal btn-block" %>
              </div>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">

    <div style="margin-bottom: 30px;">
      <div class="col-md-5 text-center d-grid gap-2 col-6 mx-auto d-flex">
        <%= link_to " ルーム登録", new_room_path, class: "btn btn-default" %>
        </br>
        </br>
        <%= link_to " 登録ルーム一覧", rooms_path, class: "btn btn-default" %>
        </br>
        </br>
        <%= link_to " 予約ルーム一覧", bookings_path, class: "btn btn-default" %>
      </div>
    </div>

    <div class="d-flex">
      <div class="col-md-7">
        <div class="card card-default">
          <div class="card-heading align-middle text-center">
            予約情報
          </div>
          <div class="card-body">
            <div class="container">
              <div style="margin-bottom: 20px;">
                <img src="<%= @room.image_url %>" class="img-max">
              </div>
              <div style="margin-bottom: 20px;">
                <h4><%= @room.name %></h4>
                <p><%= @room.address %></p>
              </div>
              <div>
                <h3><%= @room.introduction %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4 margin">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h3 class="form-group">&yen; <%= @room.price.to_i %> / 日</h3>

            <%= form_for @room.bookings.new do |f| %>
              <%= f.hidden_field :room_id, :value => @room.id %>
              <div class="form-group">
                <label style="margin-bottom: 5px;">開始日</label>
                <%= f.date_field :start_date,autocomplete: "開始日",class: "form-control" %>
              </div>

              <div class="form-group">
                <label style="margin-bottom: 5px;">終了日</label>
                <%= f.date_field :end_date,autocomplete: "終了日",class: "form-control" %>
              </div>

              <div class="form-group">
                <label style="margin-bottom: 5px;">人数</label>
                <%= f.number_field :person,autocomplete: "人数",class: "form-control" %>
              </div>

              <div class="actions">
                <%= f.submit "予約", class:"btn btn-blue btn-block" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></p>
      </ul>
    <% end %>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <h1>booking.com</h1>
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
            </div>
        </div>
        <div class="navbar-end">
            <a class="navbar-item"></a>
            <a class="navbar-item"></a>
            <!-- もしログインしていなかったら-->
            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "新規ユーザ登録", new_user_registration_path, class: "button is-white" %>
                        <%= link_to  "ログイン", new_user_session_path, class: "button is-white" %>
                    </div>
                </div>
            <!-- ログインしていたら　-->
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable" style="margin-right: 150px;">
                    <a class="navbar-item"><%= current_user.full_name %></a>
                    <figure class="image is-48x48 m-r-5">
                    <div style="margin-top: 0.6rem;">
                    <img src="<%="#{current_user.image_url}"%>"
                    </div>
                    </figure>
                    <div class="navbar-dropdown">
                        <%= link_to  "ルーム登録", new_room_path, class: "navbar-item" %>
                        <%= link_to "予約済みルーム一覧", bookings_path, class: "navbar-item" %>
                        <%= link_to "登録済みルーム一覧", rooms_path, class: "navbar-item" %>
                        <%= link_to "アカウント情報", edit_user_registration_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>            
        </div>
    </div>
</nav>

<script>
$(document).ready(function() {
  // navbar burgerアイコンでクリックイベントを確認する
  $(".navbar-burger").click(function() {
      // 「navbar-burger」と「navbar-menu」の両方で「is-active」クラスを切り替える
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");
  });
});
</script>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-2">
      <ul class="sidebar">
        <li class="sidebar-item text-center"><%= link_to "プロフィール確認", user_path(current_user.id), class: "sidebar-link active btn btn-default" %></li>
      </ul>
      <%= link_to "プロフィール編集", edit_user_registration_path, class: "btn btn-default" %>
    </div>

    <div class="col-md-7 text-center margin">
      <div class="card card-default">
        <div class="card-heading text-center">プロフィール確認</div>
        </br>
        <div class="card-body">
          <h2><%= @user.full_name %></h2>
          </br>
          <div class="email">メールアドレス</div><%= @user.email %>
          </br>
          <div class="introduction">自己紹介</div><%= @user.introduction %>
          </br>
          <img src="<%="#{current_user.image_url}"%>" class="img-fluid-show" alt="image">
          </div>
        </div>
        
      </div>
    </div>